apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-instance
  namespace: monitoring-system
  labels:
    dashboards: "grafana"
spec:
  dashboardLabelSelector:
    matchLabels:
      app: grafana  
  ingress:
    enabled: true
    targetPort: grafana # Name des Ports im Service
    termination: edge           # Aktiviert TLS (HTTPS) am Router
    host: grafana-web-monitoring-system.apps-crc.testing
  config:
    server:
      root_url: https://%(domain)s/ # Wichtig für korrekte Redirects
    log:
      mode: "console"
    auth.anonymous:
      enabled: "true"
      orgRole: "Admin"